# Generated by Django 3.2.10 on 2024-01-04 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='propertes/property', verbose_name='Image')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenant',
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantUnitAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_end_date', models.DateTimeField()),
                ('monthly_rent_date', models.CharField(max_length=2)),
                ('attachement', models.FileField(blank=True, null=True, upload_to='tenant_unit/document')),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
            options={
                'verbose_name': 'Tenant Assigned Unit',
                'verbose_name_plural': 'Tenant Assigned Unit',
                'db_table': 'tenant_assigned_unit',
            },
        ),
        migrations.CreateModel(
            name='TenantDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('010', 'Adhar Card'), ('015', 'Driving Licence'), ('020', 'Voter ID'), ('025', 'Passport')], max_length=3)),
                ('document', models.FileField(upload_to='tenant/document')),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Documents',
                'verbose_name_plural': 'Tenant Documents',
                'db_table': 'tenant_documents',
            },
        ),
    ]
