# Generated by Django 3.2.10 on 2024-01-04 06:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('features', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=256)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='propertes/property', verbose_name='Image')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Property',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('rent_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('main_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='units/main_images', verbose_name='Image')),
                ('is_deleted', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
                'db_table': 'units',
            },
        ),
    ]
