# Generated by Django 3.2.10 on 2024-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('010', '1BHK'), ('015', '2BHK'), ('020', '3BHK'), ('025', '4BHK'), ('030', '5BHK'), ('035', '6BHK')], max_length=3),
        ),
    ]
